apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-api-account
  namespace: monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: monitoring
  name: open-api-service-reader
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - 'metrics.k8s.io'
    resources:
      - pods
      - nodes
      - nodes/stats
      - namespaces
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - deployments
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: open-api-service-reader
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: open-api-account
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: open-api-service-reader
  apiGroup: rbac.authorization.k8s.io