# Declaring the user list
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: monitoring
spec:
  basicAuth:
    headerField: BC-WebAuth-User
    secret: auth-secret
    removeHeader: true